import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'kalkulator-peluang-menarik-kartu', title: 'Kalkulator Peluang Menarik Kartu',
  description: 'Hitung peluang mendapatkan setidaknya satu salinan kartu hingga giliran tertentu dengan distribusi hipergeometrik.',
  ui: {
    configureLabel: 'Atur aturan dek', configureHint: 'Ubah dek, tangan, tarikan, dan mulligan. Hasil diperbarui seketika.', presetLabel: 'Titik awal', presetCustom: 'Aturan khusus', presetStandard: 'Dek 60 kartu · 4 salinan', presetLimited: 'Dek 40 kartu · 4 salinan', presetSingleton: 'Dek 100 kartu · 1 salinan', deckSizeLabel: 'Ukuran dek', targetCopiesLabel: 'Salinan kartu', openingHandLabel: 'Tangan awal', drawsPerTurnLabel: 'Tarikan per giliran', throughTurnLabel: 'Tampilkan hingga giliran', mulliganLabel: 'Model mulligan', mulliganNone: 'Tanpa mulligan', mulliganFullRedraw: 'Tarik ulang setelah gagal', visualLabel: 'Jalur tarikanmu', visualHint: 'Kipas kartu terbuka saat lebih banyak kartu masuk ke sampel.', openingHandStage: 'Tangan awal', turnLabel: 'Giliran', cardsSeenLabel: 'Kartu terlihat', finalChanceLabel: 'Peluang pada giliran akhir', expectedCopiesLabel: 'Salinan yang diharapkan', probabilityByTurnLabel: 'Peluang tiap giliran', explanationLabel: 'Setidaknya satu salinan', noMulliganNote: 'Tanpa mulligan: model menghitung satu sampel dari dek yang dikocok.', fullRedrawNote: 'Tarik ulang setelah gagal: jika tangan awal tidak memiliki salinan target, seluruh tangan diganti sekali.', invalidInput: 'Periksa aturan dek untuk melanjutkan.', invalidDeck: 'Pilih ukuran dek yang valid.', invalidCopies: 'Jumlah salinan harus antara nol dan ukuran dek.', invalidHand: 'Tangan awal tidak boleh lebih besar dari dek.', invalidDraws: 'Tarikan per giliran harus nol atau lebih.', invalidTurns: 'Pilih giliran antara nol dan 60.', cardsLabel: 'kartu', copyLabel: 'salinan',
  },
  seo: [
    { type: 'title', level: 2, text: 'Hitung peluang tarikan kartu untuk dek tabletop' },
    { type: 'paragraph', html: 'Kalkulator ini menjawab pertanyaan praktis saat menyusun dek: seberapa besar peluang melihat setidaknya satu salinan kartu sebelum giliran tertentu? Masukkan ukuran dek, salinan, tangan awal, tarikan, dan aturan mulligan untuk melihat persentase tiap giliran.' },
    { type: 'paragraph', html: 'Distribusi hipergeometrik digunakan karena kartu ditarik tanpa pengembalian. Model ini cocok untuk permainan kartu koleksi, permainan papan, dek limited, dan kumpulan kartu terbatas lainnya.' },
    { type: 'title', level: 2, text: 'Cara membaca garis waktu tarikan' },
    { type: 'list', items: ['Tangan awal adalah sampel pertama dari dek yang dikocok.', 'Setiap giliran menambahkan jumlah kartu yang ditarik.', 'Persentase berarti melihat setidaknya satu salinan, bukan tepat satu.', 'Salinan yang diharapkan adalah rata-rata terpisah dari peluang mengenai target.'] },
    { type: 'title', level: 2, text: 'Asumsi mulligan dapat diubah' },
    { type: 'paragraph', html: 'Pilihan tarik ulang memodelkan strategi sederhana: simpan tangan jika berisi target; jika tidak, ganti seluruh tangan sekali lalu lanjutkan dari jalur pengganti. Mulligan sebagian, scry, tutor, dan keputusan berdasarkan kartu lain tidak dimodelkan.' },
    { type: 'tip', title: 'Gunakan aturan permainanmu', html: 'Jika permainanmu memiliki tangan awal, tarikan tambahan, atau prosedur mulligan yang berbeda, ubah kolom tersebut. Jawaban bergantung pada aturan dan jumlah salinan di dek.' },
    { type: 'title', level: 2, text: 'Gagasan hipergeometrik dalam satu baris' },
    { type: 'paragraph', html: 'Untuk n kartu dari dek N yang berisi K salinan target, peluang tanpa target adalah C(N − K, n) / C(N, n). Kalkulator memakai komplemennya, 1 − peluang tanpa target, untuk mendapatkan peluang setidaknya satu kartu target.' },
    { type: 'diagnostic', variant: 'info', title: 'Yang tidak disimulasikan kalkulator ini', badge: 'BATASAN', html: 'Kartu bernama, pemilihan kartu, efek pengganti, scry, tutor, beberapa target, dan keadaan permainan penuh tidak dilacak. Gunakan hasil ini sebagai dasar lalu modelkan aturan tambahan secara terpisah.' },
  ],
  faq: [{ question: 'Apa rumus peluang menarik kartu?', answer: 'Untuk setidaknya satu salinan dalam n kartu, kalkulator memakai 1 − C(N − K, n) / C(N, n), dengan N sebagai ukuran dek dan K sebagai jumlah salinan.' }, { question: 'Apakah ini bekerja untuk tarikan 5 kartu?', answer: 'Ya. Atur Tangan awal menjadi 5 dan pilih tarikan serta giliran sesuai permainanmu.' }, { question: 'Bagaimana opsi mulligan bekerja?', answer: 'Tarik ulang setelah gagal mengganti satu kali seluruh tangan awal yang tidak memiliki salinan target. Model ini sengaja lebih sederhana daripada aturan tiap permainan.' }, { question: 'Mengapa salinan yang diharapkan berbeda dari peluang berhasil?', answer: 'Peluang berhasil menanyakan apakah sampel berisi satu atau lebih salinan. Salinan yang diharapkan adalah jumlah rata-rata salinan dalam sampel.' }],
  bibliography, howTo: [{ name: 'Masukkan ukuran dek dan salinan', text: 'Tentukan jumlah seluruh kartu dan jumlah salinan kartu yang ingin ditarik.' }, { name: 'Sesuaikan tangan dan tarikan', text: 'Masukkan ukuran tangan awal, kartu per giliran, dan giliran terakhir.' }, { name: 'Pilih model mulligan', text: 'Gunakan Tanpa mulligan untuk satu sampel berkelanjutan atau tarik ulang setelah gagal untuk satu penggantian penuh.' }, { name: 'Baca garis waktu', text: 'Bandingkan persentase setidaknya satu salinan pada tangan awal dan tiap giliran.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Kalkulator Peluang Menarik Kartu', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Peluang tarikan kartu untuk dek tabletop terbatas.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Apa rumus peluang menarik kartu?', acceptedAnswer: { '@type': 'Answer', text: 'Kalkulator memakai komplemen peluang hipergeometrik tanpa target.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Menghitung peluang tarikan kartu', step: [{ '@type': 'HowToStep', name: 'Atur aturan dek', text: 'Masukkan ukuran dek, salinan, tangan, tarikan, dan giliran.' }, { '@type': 'HowToStep', name: 'Baca hasil', text: 'Bandingkan peluang melihat setidaknya satu salinan pada garis waktu.' }] }],
};
