import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'calcolatore-probabilita-pescare-carte', title: 'Calcolatore della probabilità di pescare carte',
  description: 'Calcola con la distribuzione ipergeometrica la probabilità di pescare almeno una copia di una carta entro un turno preciso.',
  ui: {
    configureLabel: 'Imposta le regole del mazzo', configureHint: 'Modifica mazzo, mano, pescate e mulligan. I risultati cambiano subito.', presetLabel: 'Punto di partenza', presetCustom: 'Regole personalizzate', presetStandard: 'Mazzo da 60 · 4 copie', presetLimited: 'Mazzo da 40 · 4 copie', presetSingleton: 'Mazzo da 100 · 1 copia', deckSizeLabel: 'Dimensione del mazzo', targetCopiesLabel: 'Copie della carta', openingHandLabel: 'Mano iniziale', drawsPerTurnLabel: 'Pescate per turno', throughTurnLabel: 'Mostra fino al turno', mulliganLabel: 'Modello di mulligan', mulliganNone: 'Nessun mulligan', mulliganFullRedraw: 'Ripesca dopo un errore', visualLabel: 'Il tuo percorso di pesca', visualHint: 'Il ventaglio si apre quando altre carte entrano nel campione.', openingHandStage: 'Mano iniziale', turnLabel: 'Turno', cardsSeenLabel: 'Carte viste', finalChanceLabel: 'Probabilità al turno finale', expectedCopiesLabel: 'Copie attese fino a quel punto', probabilityByTurnLabel: 'Probabilità per turno', explanationLabel: 'Almeno una copia', noMulliganNote: 'Senza mulligan: il modello conta un solo campione dal mazzo mischiato.', fullRedrawNote: 'Ripesca dopo un errore: se la mano iniziale non contiene la copia cercata, viene sostituita una volta.', invalidInput: 'Controlla le regole del mazzo per continuare.', invalidDeck: 'Scegli una dimensione del mazzo valida.', invalidCopies: 'Le copie devono essere tra zero e la dimensione del mazzo.', invalidHand: 'La mano iniziale non può superare il mazzo.', invalidDraws: 'Le pescate per turno devono essere almeno zero.', invalidTurns: 'Scegli un turno tra zero e 60.', cardsLabel: 'carte', copyLabel: 'copie',
  },
  seo: [{ type: 'title', level: 2, text: 'Calcola le probabilità di pesca del tuo mazzo' }, { type: 'paragraph', html: 'Questo calcolatore risponde a una domanda utile per chi costruisce un mazzo: qual è la probabilità di vedere almeno una copia di una carta entro un certo turno? Inserisci dimensione, copie, mano iniziale, pescate e mulligan per ottenere il valore turno per turno.' }, { type: 'paragraph', html: 'La distribuzione ipergeometrica è adatta perché le carte vengono pescate senza reinserimento. È utile per giochi di carte collezionabili, giochi da tavolo, mazzi limited e altri insiemi finiti.' }, { type: 'title', level: 2, text: 'Come leggere la sequenza di pesca' }, { type: 'list', items: ['La mano iniziale è il primo campione del mazzo mischiato.', 'Ogni turno aggiunge il numero di carte pescate impostato.', 'La percentuale indica almeno una copia, non esattamente una.', 'Le copie attese sono una media diversa dalla probabilità di trovare il bersaglio.'] }, { type: 'title', level: 2, text: 'Le ipotesi del mulligan sono configurabili' }, { type: 'paragraph', html: 'La ripesca rappresenta una strategia semplice: tieni una mano che contiene il bersaglio; altrimenti sostituiscila interamente una volta e prosegui dal nuovo percorso. Non include mulligan parziali, scry, tutor o decisioni sulle altre carte.' }, { type: 'tip', title: 'Usa le regole del tuo gioco', html: 'Se il gioco ha una mano iniziale diversa, una pescata extra o un mulligan particolare, modifica questi campi. La risposta dipende dalle regole e dal numero di copie.' }, { type: 'title', level: 2, text: 'L\'idea ipergeometrica in una riga' }, { type: 'paragraph', html: 'Per n carte da un mazzo di N con K copie bersaglio, la probabilità di non trovare il bersaglio è C(N − K, n) / C(N, n). Il calcolatore usa il complemento 1 − questa probabilità per ottenere almeno una copia.' }, { type: 'diagnostic', variant: 'info', title: 'Cosa non simula questo calcolatore', badge: 'LIMITI', html: 'Non segue carte nominate, selezione, effetti di sostituzione, scry, tutor, più bersagli o lo stato completo della partita. Usa il risultato come base e aggiungi le regole speciali separatamente.' }],
  faq: [{ question: 'Qual è la formula della probabilità di pesca?', answer: 'Per almeno una copia in n carte si usa 1 − C(N − K, n) / C(N, n), dove N è la dimensione del mazzo e K il numero di copie.' }, { question: 'Funziona per una mano di 5 carte?', answer: 'Sì. Imposta la mano iniziale su 5 e scegli pescate e turni coerenti con il gioco.' }, { question: 'Come funziona il mulligan?', answer: 'Ripesca dopo un errore sostituisce una volta una mano senza la carta bersaglio. È un modello più semplice delle regole specifiche dei giochi.' }, { question: 'Perché le copie attese sono diverse dalla probabilità di trovare la carta?', answer: 'La probabilità chiede se il campione contiene una o più copie. Le copie attese sono il numero medio di copie nel campione.' }],
  bibliography, howTo: [{ name: 'Inserisci dimensione e copie', text: 'Imposta il numero totale di carte e le copie che vuoi pescare.' }, { name: 'Adatta mano e pescate', text: 'Inserisci mano iniziale, carte pescate per turno e turno finale.' }, { name: 'Scegli il modello di mulligan', text: 'Usa Nessun mulligan per un campione continuo oppure la ripesca per una sostituzione completa.' }, { name: 'Leggi la sequenza', text: 'Confronta la percentuale di almeno una copia nella mano e in ogni turno.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Calcolatore della probabilità di pescare carte', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Probabilità di pesca per mazzi tabletop finiti.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Qual è la formula della probabilità di pesca?', acceptedAnswer: { '@type': 'Answer', text: 'Il calcolatore usa il complemento della probabilità ipergeometrica senza bersaglio.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Calcolare le probabilità di pesca', step: [{ '@type': 'HowToStep', name: 'Imposta le regole', text: 'Inserisci dimensione, copie, mano, pescate e turni.' }, { '@type': 'HowToStep', name: 'Leggi il risultato', text: 'Confronta nella sequenza la probabilità di vedere almeno una copia.' }] }],
};
