import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'card-draw-odds-calculator', title: 'カードを引く確率計算機',
  description: '超幾何分布を使って、指定したターンまでにカードを1枚以上引く確率を計算します。',
  ui: {
    configureLabel: 'デッキのルールを設定', configureHint: 'デッキ、初期手札、ドロー、マリガンを変更すると結果がすぐ更新されます。', presetLabel: 'スタート地点', presetCustom: 'カスタムルール', presetStandard: '60枚デッキ · 4枚', presetLimited: '40枚デッキ · 4枚', presetSingleton: '100枚デッキ · 1枚', deckSizeLabel: 'デッキ枚数', targetCopiesLabel: '対象カードの枚数', openingHandLabel: '初期手札', drawsPerTurnLabel: '1ターンのドロー', throughTurnLabel: '表示するターン', mulliganLabel: 'マリガンモデル', mulliganNone: 'マリガンなし', mulliganFullRedraw: '外れたら引き直す', visualLabel: 'ドローの流れ', visualHint: 'サンプルにカードが増えるほどカードの扇が開きます。', openingHandStage: '初期手札', turnLabel: 'ターン', cardsSeenLabel: '見たカード', finalChanceLabel: '最終ターンまでの確率', expectedCopiesLabel: 'その時点の期待枚数', probabilityByTurnLabel: 'ターンごとの確率', explanationLabel: '1枚以上', noMulliganNote: 'マリガンなし: シャッフルしたデッキから1つのサンプルを数えます。', fullRedrawNote: '外れたら引き直す: 初期手札に対象がなければ1回だけ全交換します。', invalidInput: 'デッキの設定を確認してください。', invalidDeck: '有効なデッキ枚数を入力してください。', invalidCopies: '対象枚数は0枚以上、デッキ枚数以下にしてください。', invalidHand: '初期手札はデッキ枚数を超えられません。', invalidDraws: '1ターンのドローは0以上にしてください。', invalidTurns: '0から60までのターンを選んでください。', cardsLabel: '枚', copyLabel: '枚',
  },
  seo: [{ type: 'title', level: 2, text: 'デッキからカードを引く確率を計算' }, { type: 'paragraph', html: 'この計算機は、特定のターンまでに欲しいカードを1枚以上見られる確率を求めます。デッキ枚数、採用枚数、初期手札、毎ターンのドロー、マリガンを入力して、ターンごとの変化を確認できます。' }, { type: 'paragraph', html: 'カードは戻さずに引くため、超幾何分布を使います。トレーディングカードゲーム、ボードゲーム、リミテッドなど有限のカードプールに利用できます。' }, { type: 'title', level: 2, text: 'ドローのタイムラインを読む' }, { type: 'list', items: ['初期手札はシャッフル後の最初のサンプルです。', '各ターンに設定した枚数が追加されます。', '表示される割合は1枚以上であり、ちょうど1枚ではありません。', '期待枚数は別の平均値で、ヒット率とは異なります。'] }, { type: 'title', level: 2, text: 'マリガンの前提を変更' }, { type: 'paragraph', html: '引き直しは、対象を含む手札をキープし、対象がなければ手札全体を1回交換する簡単なモデルです。部分的なマリガン、占術、サーチ、他のカードを見た判断は含みません。' }, { type: 'tip', title: 'ゲームのルールに合わせる', html: '初期手札や追加ドロー、マリガン手順が異なる場合は入力を変更してください。結果はルールと対象カードの枚数に左右されます。' }, { type: 'title', level: 2, text: '超幾何分布を一行で説明' }, { type: 'paragraph', html: 'N枚のデッキに対象がK枚あり、n枚を見るとき、対象がない確率は C(N − K, n) / C(N, n) です。計算機はその補数 1 − その確率を使って1枚以上の確率を表示します。' }, { type: 'diagnostic', variant: 'info', title: '計算機で扱わないもの', badge: '制限', html: 'カード名、選択効果、交換効果、占術、サーチ、複数の対象、ゲーム全体の状態は追跡しません。結果を基準値として使い、追加ルールは別に考えてください。' }],
  faq: [{ question: 'カードを引く確率の式は何ですか？', answer: 'n枚中に1枚以上ある確率として、1 − C(N − K, n) / C(N, n) を使います。Nはデッキ枚数、Kは対象カードの枚数です。' }, { question: '5枚ドローにも使えますか？', answer: 'はい。初期手札を5にして、ゲームに合わせてドロー数とターンを設定してください。' }, { question: 'マリガンはどう計算しますか？', answer: '外れたら引き直すでは、対象のない初期手札を1回だけ全交換します。ゲーム固有の部分交換より単純なモデルです。' }, { question: '期待枚数とヒット率が違うのはなぜですか？', answer: 'ヒット率は1枚以上あるかを問い、期待枚数はサンプル内の平均枚数を表すためです。' }],
  bibliography, howTo: [{ name: 'デッキ枚数と対象枚数を入力', text: 'デッキ全体の枚数と探しているカードの枚数を設定します。' }, { name: '手札とドローを合わせる', text: '初期手札、1ターンのドロー、最後のターンを入力します。' }, { name: 'マリガンモデルを選ぶ', text: '連続したサンプルにはマリガンなし、全交換には外れたら引き直すを使います。' }, { name: 'タイムラインを読む', text: '初期手札と各ターンで1枚以上引く確率を比べます。' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'カードを引く確率計算機', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: '有限のカードデッキ向けドロー確率計算機。' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'カードを引く確率の式は何ですか？', acceptedAnswer: { '@type': 'Answer', text: '対象がない超幾何確率の補数を使います。' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'カードを引く確率を計算する', step: [{ '@type': 'HowToStep', name: 'ルールを設定', text: 'デッキ、対象枚数、手札、ドロー、ターンを入力します。' }, { '@type': 'HowToStep', name: '結果を読む', text: 'タイムラインで1枚以上の確率を比べます。' }] }],
};
