import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'card-draw-odds-calculator', title: '카드 드로우 확률 계산기',
  description: '초기 손패와 턴별 드로우 규칙을 바탕으로 특정 턴까지 카드 한 장 이상을 뽑을 확률을 계산합니다.',
  ui: {
    configureLabel: '덱 규칙 설정', configureHint: '덱, 손패, 드로우, 멀리건을 바꾸면 결과가 즉시 갱신됩니다.', presetLabel: '시작점', presetCustom: '사용자 지정 규칙', presetStandard: '60장 덱 · 4장', presetLimited: '40장 덱 · 4장', presetSingleton: '100장 덱 · 1장', deckSizeLabel: '덱 크기', targetCopiesLabel: '대상 카드 수', openingHandLabel: '초기 손패', drawsPerTurnLabel: '턴당 드로우', throughTurnLabel: '표시할 턴', mulliganLabel: '멀리건 모델', mulliganNone: '멀리건 없음', mulliganFullRedraw: '실패 후 다시 뽑기', visualLabel: '드로우 경로', visualHint: '표본에 카드가 추가될수록 카드 부채가 펼쳐집니다.', openingHandStage: '초기 손패', turnLabel: '턴', cardsSeenLabel: '본 카드', finalChanceLabel: '마지막 턴까지의 확률', expectedCopiesLabel: '예상 카드 수', probabilityByTurnLabel: '턴별 확률', explanationLabel: '한 장 이상', noMulliganNote: '멀리건 없음: 섞인 덱에서 하나의 표본을 계산합니다.', fullRedrawNote: '실패 후 다시 뽑기: 초기 손패에 대상이 없으면 한 번 전체 교체합니다.', invalidInput: '계속하려면 덱 설정을 확인하세요.', invalidDeck: '올바른 덱 크기를 선택하세요.', invalidCopies: '카드 수는 0 이상이며 덱 크기 이하여야 합니다.', invalidHand: '초기 손패는 덱보다 클 수 없습니다.', invalidDraws: '턴당 드로우는 0 이상이어야 합니다.', invalidTurns: '0에서 60 사이의 턴을 선택하세요.', cardsLabel: '장', copyLabel: '장',
  },
  seo: [{ type: 'title', level: 2, text: '덱에서 카드를 뽑을 확률 계산하기' }, { type: 'paragraph', html: '이 계산기는 특정 턴까지 원하는 카드가 한 장 이상 손에 들어올 확률을 보여 줍니다. 덱 크기, 카드 수, 초기 손패, 턴당 드로우와 멀리건 규칙을 입력해 턴별 변화를 확인하세요.' }, { type: 'paragraph', html: '카드를 다시 넣지 않고 뽑기 때문에 초등적인 초정밀 분포인 초등하이퍼지오메트릭 분포를 사용합니다. 카드 게임, 보드게임, 리미티드 덱처럼 유한한 카드 묶음에 적합합니다.' }, { type: 'title', level: 2, text: '드로우 타임라인 읽기' }, { type: 'list', items: ['초기 손패는 섞인 덱에서 얻는 첫 표본입니다.', '각 턴에 설정한 카드 수가 더해집니다.', '백분율은 정확히 한 장이 아니라 한 장 이상을 뜻합니다.', '예상 카드 수는 적중 확률과 다른 평균값입니다.'] }, { type: 'title', level: 2, text: '멀리건 가정 설정하기' }, { type: 'paragraph', html: '다시 뽑기 옵션은 대상 카드가 있는 손패는 유지하고, 없으면 손패 전체를 한 번 교체하는 간단한 전략을 모델링합니다. 부분 멀리건, 점술, 서치와 다른 카드에 따른 판단은 포함하지 않습니다.' }, { type: 'tip', title: '게임 규칙에 맞추세요', html: '초기 손패, 추가 드로우 또는 멀리건 절차가 다르다면 입력값을 바꾸세요. 결과는 규칙과 카드 수에 따라 달라집니다.' }, { type: 'title', level: 2, text: '초기하이퍼지오메트릭 아이디어 한 줄' }, { type: 'paragraph', html: 'N장 덱에 대상 카드 K장이 있고 n장을 볼 때 대상이 없을 확률은 C(N − K, n) / C(N, n)입니다. 계산기는 그 여집합을 사용해 한 장 이상일 확률을 보여 줍니다.' }, { type: 'diagnostic', variant: 'info', title: '계산하지 않는 항목', badge: '제한', html: '카드 이름, 선택 효과, 교체 효과, 점술, 서치, 여러 대상과 전체 게임 상태는 추적하지 않습니다. 결과를 기준값으로 사용하고 추가 규칙은 따로 모델링하세요.' }],
  faq: [{ question: '카드 드로우 확률 공식은 무엇인가요?', answer: 'n장 중 한 장 이상일 확률인 1 − C(N − K, n) / C(N, n)을 사용합니다. N은 덱 크기, K는 대상 카드 수입니다.' }, { question: '5장 드로우에도 사용할 수 있나요?', answer: '네. 초기 손패를 5로 설정하고 게임에 맞는 드로우와 턴을 선택하세요.' }, { question: '멀리건 옵션은 어떻게 계산하나요?', answer: '실패 후 다시 뽑기는 대상이 없는 초기 손패를 한 번 전체 교체하는 모델입니다.' }, { question: '예상 카드 수와 적중 확률이 다른 이유는 무엇인가요?', answer: '적중 확률은 한 장 이상 있는지를 묻고, 예상 카드 수는 표본 안의 평균 장수를 나타냅니다.' }],
  bibliography, howTo: [{ name: '덱과 대상 카드 수 입력', text: '전체 덱 크기와 찾으려는 카드 수를 설정합니다.' }, { name: '손패와 드로우 규칙 맞추기', text: '초기 손패, 턴당 카드 수와 마지막 턴을 입력합니다.' }, { name: '멀리건 모델 선택', text: '연속 표본에는 멀리건 없음을, 전체 교체에는 실패 후 다시 뽑기를 사용합니다.' }, { name: '타임라인 읽기', text: '초기 손패와 각 턴의 한 장 이상 확률을 비교합니다.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: '카드 드로우 확률 계산기', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: '유한한 tabletop 덱을 위한 카드 드로우 확률 계산기.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: '카드 드로우 확률 공식은 무엇인가요?', acceptedAnswer: { '@type': 'Answer', text: '대상이 없을 확률의 여집합인 초기하이퍼지오메트릭 확률을 사용합니다.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: '카드 드로우 확률 계산하기', step: [{ '@type': 'HowToStep', name: '덱 규칙 설정', text: '덱, 카드 수, 손패, 드로우와 턴을 입력합니다.' }, { '@type': 'HowToStep', name: '결과 확인', text: '타임라인에서 한 장 이상일 확률을 비교합니다.' }] }],
};
