import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'kans-kaart-trekken-calculator', title: 'Calculator voor de kans op kaarten trekken',
  description: 'Bereken met de hypergeometrische verdeling de kans om vóór een bepaalde beurt minstens één exemplaar van een kaart te trekken.',
  ui: {
    configureLabel: 'Stel je deckregels in', configureHint: 'Pas deck, hand, trekken en mulligan aan. Resultaten worden direct bijgewerkt.', presetLabel: 'Startpunt', presetCustom: 'Aangepaste regels', presetStandard: 'Deck van 60 · 4 exemplaren', presetLimited: 'Deck van 40 · 4 exemplaren', presetSingleton: 'Deck van 100 · 1 exemplaar', deckSizeLabel: 'Deckgrootte', targetCopiesLabel: 'Exemplaren van de kaart', openingHandLabel: 'Openingshand', drawsPerTurnLabel: 'Kaarten per beurt', throughTurnLabel: 'Tonen tot beurt', mulliganLabel: 'Mulliganmodel', mulliganNone: 'Geen mulligan', mulliganFullRedraw: 'Opnieuw na misser', visualLabel: 'Jouw trekpad', visualHint: 'De waaier opent wanneer er meer kaarten in de steekproef komen.', openingHandStage: 'Openingshand', turnLabel: 'Beurt', cardsSeenLabel: 'Geziene kaarten', finalChanceLabel: 'Kans bij de laatste beurt', expectedCopiesLabel: 'Verwachte exemplaren tot dan', probabilityByTurnLabel: 'Kans per beurt', explanationLabel: 'Minstens één exemplaar', noMulliganNote: 'Geen mulligan: het model telt één steekproef uit het geschudde deck.', fullRedrawNote: 'Opnieuw na misser: een openingshand zonder doelkaart wordt één keer volledig vervangen.', invalidInput: 'Controleer de deckregels om door te gaan.', invalidDeck: 'Kies een geldige deckgrootte.', invalidCopies: 'Exemplaren moeten tussen nul en de deckgrootte liggen.', invalidHand: 'De openingshand mag niet groter zijn dan het deck.', invalidDraws: 'Kaarten per beurt moeten nul of meer zijn.', invalidTurns: 'Kies een beurt tussen nul en 60.', cardsLabel: 'kaarten', copyLabel: 'exemplaren',
  },
  seo: [{ type: 'title', level: 2, text: 'Bereken de kans om kaarten uit je deck te trekken' }, { type: 'paragraph', html: 'Deze calculator beantwoordt een praktische vraag voor deckbouwers: hoe groot is de kans dat je vóór een bepaalde beurt minstens één exemplaar van een kaart ziet? Vul deckgrootte, exemplaren, openingshand, trekken en mulligan in voor een overzicht per beurt.' }, { type: 'paragraph', html: 'De hypergeometrische verdeling past omdat kaarten zonder terugleggen worden getrokken. Daardoor werkt het model voor ruilkaartspellen, bordspellen, limited-decks en andere eindige kaartverzamelingen.' }, { type: 'title', level: 2, text: 'De trek-tijdlijn lezen' }, { type: 'list', items: ['De openingshand is de eerste steekproef uit het geschudde deck.', 'Elke beurt voegt het ingestelde aantal getrokken kaarten toe.', 'Het percentage betekent minstens één exemplaar, niet precies één.', 'Verwachte exemplaren zijn een apart gemiddelde en meten iets anders dan de trefkans.'] }, { type: 'title', level: 2, text: 'Mulliganaannames zijn instelbaar' }, { type: 'paragraph', html: 'Opnieuw trekken modelleert een eenvoudige strategie: houd een hand met de doelkaart; anders vervang je de hele hand één keer en ga je verder met het vervangende pad. Gedeeltelijke mulligans, scry, tutors en keuzes rond andere kaarten zitten er niet in.' }, { type: 'tip', title: 'Gebruik de regels van jouw spel', html: 'Heeft je spel een andere openingshand, extra trekstap of mulliganprocedure? Pas die velden aan. Het exacte antwoord hangt af van de regels en het aantal exemplaren.' }, { type: 'title', level: 2, text: 'Het hypergeometrische idee in één regel' }, { type: 'paragraph', html: 'Voor n kaarten uit een deck van N met K doel-exemplaren is de kans zonder doelkaart C(N − K, n) / C(N, n). De calculator gebruikt het complement 1 − die kans voor minstens één doelkaart.' }, { type: 'diagnostic', variant: 'info', title: 'Wat deze calculator niet simuleert', badge: 'GRENZEN', html: 'Benoemde kaarten, selectie, vervangingseffecten, scry, tutors, meerdere doelen en een volledige spelstaat worden niet bijgehouden. Gebruik dit als basis en modelleer extra regels apart.' }],
  faq: [{ question: 'Welke formule gebruikt de kaarttrekkans?', answer: 'Voor minstens één exemplaar in n kaarten gebruikt de calculator 1 − C(N − K, n) / C(N, n), met N als deckgrootte en K als aantal exemplaren.' }, { question: 'Werkt dit voor vijf getrokken kaarten?', answer: 'Ja. Zet Openingshand op 5 en kies trekken en beurten die bij je spel passen.' }, { question: 'Hoe werkt de mulliganoptie?', answer: 'Opnieuw na misser vervangt één keer een openingshand zonder doelkaart. Het is eenvoudiger dan de specifieke gedeeltelijke regels van een spel.' }, { question: 'Waarom verschilt het verwachte aantal exemplaren van de trefkans?', answer: 'De trefkans vraagt of de steekproef één of meer exemplaren bevat. Verwachte exemplaren is het gemiddelde aantal in die steekproef.' }],
  bibliography, howTo: [{ name: 'Vul deckgrootte en exemplaren in', text: 'Stel het totale aantal kaarten en het aantal gewenste exemplaren in.' }, { name: 'Pas hand en trekken aan', text: 'Vul openingshand, kaarten per beurt en de laatste beurt in.' }, { name: 'Kies een mulliganmodel', text: 'Gebruik Geen mulligan voor één doorlopende steekproef of Opnieuw na misser voor één volledige vervanging.' }, { name: 'Lees de tijdlijn', text: 'Vergelijk het percentage van minstens één exemplaar in de hand en per beurt.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Calculator voor de kans op kaarten trekken', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Kaarttrekkansen voor eindige tabletop-decks.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Welke formule gebruikt de kaarttrekkans?', acceptedAnswer: { '@type': 'Answer', text: 'De calculator gebruikt het complement van de hypergeometrische kans zonder doelkaart.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Kaarttrekkansen berekenen', step: [{ '@type': 'HowToStep', name: 'Stel deckregels in', text: 'Vul deckgrootte, exemplaren, hand, trekken en beurten in.' }, { '@type': 'HowToStep', name: 'Lees het resultaat', text: 'Vergelijk de kans op minstens één exemplaar in de tijdlijn.' }] }],
};
