import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'kalkulator-prawdopodobienstwa-doboru-karty', title: 'Kalkulator prawdopodobieństwa dobrania karty',
  description: 'Oblicz rozkładem hipergeometrycznym szansę dobrania co najmniej jednej kopii karty do wybranej tury.',
  ui: {
    configureLabel: 'Ustaw zasady talii', configureHint: 'Zmień talię, rękę, dobieranie i mulligan. Wynik aktualizuje się od razu.', presetLabel: 'Punkt wyjścia', presetCustom: 'Własne zasady', presetStandard: 'Talia 60 kart · 4 kopie', presetLimited: 'Talia 40 kart · 4 kopie', presetSingleton: 'Talia 100 kart · 1 kopia', deckSizeLabel: 'Rozmiar talii', targetCopiesLabel: 'Kopie karty', openingHandLabel: 'Ręka początkowa', drawsPerTurnLabel: 'Dobierane karty na turę', throughTurnLabel: 'Pokaż do tury', mulliganLabel: 'Model mulliganu', mulliganNone: 'Bez mulliganu', mulliganFullRedraw: 'Wymień po pudle', visualLabel: 'Twoja ścieżka dobierania', visualHint: 'Wachlarz otwiera się, gdy próbka obejmuje kolejne karty.', openingHandStage: 'Ręka początkowa', turnLabel: 'Tura', cardsSeenLabel: 'Widziane karty', finalChanceLabel: 'Szansa w ostatniej turze', expectedCopiesLabel: 'Oczekiwane kopie do tego momentu', probabilityByTurnLabel: 'Prawdopodobieństwo według tury', explanationLabel: 'Co najmniej jedna kopia', noMulliganNote: 'Bez mulliganu: model liczy jedną próbkę z potasowanej talii.', fullRedrawNote: 'Wymiana po pudle: ręka bez celu jest raz wymieniana w całości.', invalidInput: 'Sprawdź zasady talii, aby kontynuować.', invalidDeck: 'Wybierz prawidłowy rozmiar talii.', invalidCopies: 'Liczba kopii musi mieścić się między zerem a rozmiarem talii.', invalidHand: 'Ręka początkowa nie może być większa od talii.', invalidDraws: 'Dobieranie na turę musi wynosić co najmniej zero.', invalidTurns: 'Wybierz turę od zera do 60.', cardsLabel: 'kart', copyLabel: 'kopii',
  },
  seo: [{ type: 'title', level: 2, text: 'Oblicz szanse dobrania karty z talii' }, { type: 'paragraph', html: 'Kalkulator odpowiada na praktyczne pytanie przy budowaniu talii: jaka jest szansa zobaczenia co najmniej jednej kopii karty do wybranej tury? Podaj rozmiar talii, kopie, rękę, dobieranie i mulligan, aby zobaczyć wynik dla każdej tury.' }, { type: 'paragraph', html: 'Rozkład hipergeometryczny pasuje, ponieważ karty są dobierane bez zwracania. Model sprawdza się w grach karcianych, planszowych, taliach limited i innych skończonych zbiorach kart.' }, { type: 'title', level: 2, text: 'Jak czytać oś dobierania' }, { type: 'list', items: ['Ręka początkowa to pierwsza próbka z potasowanej talii.', 'Każda tura dodaje ustawioną liczbę kart.', 'Procent oznacza co najmniej jedną kopię, a nie dokładnie jedną.', 'Oczekiwane kopie to osobnia średnia, inna niż szansa trafienia.'] }, { type: 'title', level: 2, text: 'Założenia mulliganu można zmienić' }, { type: 'paragraph', html: 'Wymiana po pudle przedstawia prostą strategię: zachowaj rękę z celem, a bez celu wymień całą rękę raz i kontynuuj nową ścieżką. Częściowe mulligany, scry, tutory i decyzje dotyczące innych kart nie są modelowane.' }, { type: 'tip', title: 'Użyj zasad swojej gry', html: 'Jeśli gra ma inną rękę początkową, dodatkowe dobieranie lub procedurę mulliganu, zmień odpowiednie pola. Wynik zależy od zasad i liczby kopii.' }, { type: 'title', level: 2, text: 'Idea hipergeometryczna w jednym wierszu' }, { type: 'paragraph', html: 'Dla n kart z talii N zawierającej K kopii celu szansa braku celu to C(N − K, n) / C(N, n). Kalkulator używa dopełnienia 1 − tej wartości, aby podać szansę na co najmniej jedną kopię.' }, { type: 'diagnostic', variant: 'info', title: 'Czego kalkulator nie symuluje', badge: 'OGRANICZENIA', html: 'Nie śledzi nazwanych kart, wyboru, efektów zastępowania, scry, tutorów, wielu celów ani całego stanu gry. Potraktuj wynik jako bazę i osobno zamodeluj dodatkowe zasady.' }],
  faq: [{ question: 'Jaki wzór opisuje szansę dobrania karty?', answer: 'Dla co najmniej jednej kopii w n kartach kalkulator używa 1 − C(N − K, n) / C(N, n), gdzie N to rozmiar talii, a K to liczba kopii.' }, { question: 'Czy działa dla dobrania 5 kart?', answer: 'Tak. Ustaw rękę początkową na 5 i wybierz dobieranie oraz tury zgodne z grą.' }, { question: 'Jak działa opcja mulliganu?', answer: 'Wymiana po pudle oznacza jedną pełną wymianę ręki początkowej bez karty celu. To prostszy model niż zasady konkretnej gry.' }, { question: 'Dlaczego oczekiwane kopie różnią się od szansy trafienia?', answer: 'Szansa trafienia pyta, czy próbka zawiera jedną lub więcej kopii. Oczekiwane kopie to ich średnia liczba.' }],
  bibliography, howTo: [{ name: 'Wpisz rozmiar talii i kopie', text: 'Ustaw całkowitą liczbę kart oraz liczbę szukanych kopii.' }, { name: 'Dopasuj rękę i dobieranie', text: 'Podaj rozmiar ręki, karty na turę i ostatnią turę.' }, { name: 'Wybierz model mulliganu', text: 'Użyj Bez mulliganu dla jednej próbki lub wymiany po pudle dla jednej pełnej wymiany.' }, { name: 'Przeczytaj oś czasu', text: 'Porównaj procent co najmniej jednej kopii w ręce i w każdej turze.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Kalkulator prawdopodobieństwa dobrania karty', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Szanse dobrania kart dla skończonych talii tabletop.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Jaki wzór opisuje szansę dobrania karty?', acceptedAnswer: { '@type': 'Answer', text: 'Kalkulator używa dopełnienia hipergeometrycznej szansy braku celu.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Obliczanie szans dobrania karty', step: [{ '@type': 'HowToStep', name: 'Ustaw zasady talii', text: 'Wpisz rozmiar, kopie, rękę, dobieranie i tury.' }, { '@type': 'HowToStep', name: 'Odczytaj wynik', text: 'Porównaj szansę zobaczenia co najmniej jednej kopii na osi czasu.' }] }],
};
