import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'calculadora-probabilidade-comprar-cartas', title: 'Calculadora de probabilidade de comprar cartas',
  description: 'Calcule, com a distribuição hipergeométrica, a probabilidade de comprar pelo menos uma cópia de uma carta até um turno específico.',
  ui: {
    configureLabel: 'Defina as regras do baralho', configureHint: 'Altere baralho, mão, compras e mulligan. Os resultados são atualizados na hora.', presetLabel: 'Ponto de partida', presetCustom: 'Regras personalizadas', presetStandard: 'Baralho de 60 · 4 cópias', presetLimited: 'Baralho de 40 · 4 cópias', presetSingleton: 'Baralho de 100 · 1 cópia', deckSizeLabel: 'Tamanho do baralho', targetCopiesLabel: 'Cópias da carta', openingHandLabel: 'Mão inicial', drawsPerTurnLabel: 'Compras por turno', throughTurnLabel: 'Mostrar até o turno', mulliganLabel: 'Modelo de mulligan', mulliganNone: 'Sem mulligan', mulliganFullRedraw: 'Comprar de novo após errar', visualLabel: 'Seu caminho de compra', visualHint: 'O leque se abre conforme mais cartas entram na amostra.', openingHandStage: 'Mão inicial', turnLabel: 'Turno', cardsSeenLabel: 'Cartas vistas', finalChanceLabel: 'Chance no turno final', expectedCopiesLabel: 'Cópias esperadas até lá', probabilityByTurnLabel: 'Probabilidade por turno', explanationLabel: 'Pelo menos uma cópia', noMulliganNote: 'Sem mulligan: o modelo conta uma amostra do baralho embaralhado.', fullRedrawNote: 'Comprar de novo após errar: uma mão inicial sem a carta-alvo é substituída uma vez.', invalidInput: 'Confira as regras do baralho para continuar.', invalidDeck: 'Escolha um tamanho de baralho válido.', invalidCopies: 'As cópias devem ficar entre zero e o tamanho do baralho.', invalidHand: 'A mão inicial não pode ser maior que o baralho.', invalidDraws: 'As compras por turno devem ser zero ou mais.', invalidTurns: 'Escolha um turno entre zero e 60.', cardsLabel: 'cartas', copyLabel: 'cópias',
  },
  seo: [{ type: 'title', level: 2, text: 'Calcule as chances de compra do seu baralho' }, { type: 'paragraph', html: 'Esta calculadora responde a uma pergunta útil para montar baralhos: qual é a probabilidade de ver pelo menos uma cópia de uma carta até determinado turno? Informe tamanho, cópias, mão inicial, compras e mulligan para obter uma linha por turno.' }, { type: 'paragraph', html: 'A distribuição hipergeométrica é adequada porque as cartas são compradas sem reposição. O modelo serve para jogos de cartas colecionáveis, jogos de mesa, baralhos limitados e outros conjuntos finitos.' }, { type: 'title', level: 2, text: 'Como ler a linha do tempo de compras' }, { type: 'list', items: ['A mão inicial é a primeira amostra do baralho embaralhado.', 'Cada turno acrescenta o número configurado de cartas compradas.', 'A porcentagem significa pelo menos uma cópia, não exatamente uma.', 'Cópias esperadas é uma média separada da chance de encontrar a carta.'] }, { type: 'title', level: 2, text: 'As regras do mulligan são ajustáveis' }, { type: 'paragraph', html: 'A opção de comprar novamente representa uma estratégia simples: mantenha a mão se ela tiver o alvo; caso contrário, substitua a mão inteira uma vez e continue pelo caminho da reposição. Não inclui mulligan parcial, vidência, tutores ou decisões sobre outras cartas.' }, { type: 'tip', title: 'Use as regras do seu jogo', html: 'Se o jogo tiver outra mão inicial, uma compra extra ou um mulligan diferente, altere os campos. A resposta depende das regras e do número de cópias.' }, { type: 'title', level: 2, text: 'A ideia hipergeométrica em uma linha' }, { type: 'paragraph', html: 'Para n cartas de um baralho N com K cópias-alvo, a chance de não encontrar o alvo é C(N − K, n) / C(N, n). A calculadora usa o complemento 1 − essa chance para obter pelo menos uma cópia.' }, { type: 'diagnostic', variant: 'info', title: 'O que esta calculadora não simula', badge: 'LIMITES', html: 'Ela não acompanha cartas nomeadas, seleção, efeitos de substituição, vidência, tutores, vários alvos ou o estado completo da partida. Use o resultado como base e modele regras extras à parte.' }],
  faq: [{ question: 'Qual é a fórmula da chance de comprar cartas?', answer: 'Para pelo menos uma cópia em n cartas, usa-se 1 − C(N − K, n) / C(N, n), em que N é o tamanho do baralho e K é o número de cópias.' }, { question: 'Funciona para uma compra de 5 cartas?', answer: 'Sim. Defina Mão inicial como 5 e escolha compras e turnos que correspondam ao seu jogo.' }, { question: 'Como funciona a opção de mulligan?', answer: 'Comprar de novo após errar simula uma substituição completa e única da mão inicial sem a carta-alvo. É mais simples que as regras de cada jogo.' }, { question: 'Por que cópias esperadas diferem da chance de acerto?', answer: 'A chance pergunta se a amostra tem uma ou mais cópias. Cópias esperadas é o número médio de cópias presentes na amostra.' }],
  bibliography, howTo: [{ name: 'Informe tamanho e cópias', text: 'Defina o número total de cartas e quantas cópias da carta você procura.' }, { name: 'Ajuste mão e compras', text: 'Informe a mão inicial, cartas compradas por turno e o turno final.' }, { name: 'Escolha um modelo de mulligan', text: 'Use Sem mulligan para uma amostra contínua ou comprar novamente para uma substituição completa.' }, { name: 'Leia a linha do tempo', text: 'Compare a porcentagem de pelo menos uma cópia na mão e em cada turno.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Calculadora de probabilidade de comprar cartas', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Probabilidades de compra para baralhos tabletop finitos.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Qual é a fórmula da chance de comprar cartas?', acceptedAnswer: { '@type': 'Answer', text: 'A calculadora usa o complemento da probabilidade hipergeométrica sem acerto.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Calcular chances de compra', step: [{ '@type': 'HowToStep', name: 'Defina o baralho', text: 'Informe tamanho, cópias, mão, compras e turnos.' }, { '@type': 'HowToStep', name: 'Leia o resultado', text: 'Compare na linha do tempo a chance de ver pelo menos uma cópia.' }] }],
};
