import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'kalkylator-kortdragnings-sannolikhet', title: 'Kalkylator för sannolikhet att dra kort',
  description: 'Beräkna med den hypergeometriska fördelningen chansen att dra minst ett exemplar av ett kort före en viss tur.',
  ui: {
    configureLabel: 'Ställ in kortlekens regler', configureHint: 'Ändra lek, hand, dragningar och mulligan. Resultatet uppdateras direkt.', presetLabel: 'Startpunkt', presetCustom: 'Egna regler', presetStandard: '60 kort · 4 exemplar', presetLimited: '40 kort · 4 exemplar', presetSingleton: '100 kort · 1 exemplar', deckSizeLabel: 'Kortlekens storlek', targetCopiesLabel: 'Exemplar av kortet', openingHandLabel: 'Starthand', drawsPerTurnLabel: 'Dragna kort per tur', throughTurnLabel: 'Visa till tur', mulliganLabel: 'Mulliganmodell', mulliganNone: 'Ingen mulligan', mulliganFullRedraw: 'Dra om efter miss', visualLabel: 'Din dragväg', visualHint: 'Kortsolfjädern öppnas när fler kort kommer med i urvalet.', openingHandStage: 'Starthand', turnLabel: 'Tur', cardsSeenLabel: 'Sedda kort', finalChanceLabel: 'Chans vid sista turen', expectedCopiesLabel: 'Förväntade exemplar dit', probabilityByTurnLabel: 'Sannolikhet per tur', explanationLabel: 'Minst ett exemplar', noMulliganNote: 'Ingen mulligan: modellen räknar ett urval från den blandade kortleken.', fullRedrawNote: 'Dra om efter miss: en starthand utan målkort ersätts helt en gång.', invalidInput: 'Kontrollera kortlekens regler för att fortsätta.', invalidDeck: 'Välj en giltig kortleksstorlek.', invalidCopies: 'Antalet exemplar måste ligga mellan noll och kortlekens storlek.', invalidHand: 'Starthanden får inte vara större än kortleken.', invalidDraws: 'Dragna kort per tur måste vara noll eller fler.', invalidTurns: 'Välj en tur mellan noll och 60.', cardsLabel: 'kort', copyLabel: 'exemplar',
  },
  seo: [{ type: 'title', level: 2, text: 'Beräkna sannolikheten att dra kort ur din lek' }, { type: 'paragraph', html: 'Kalkylatorn svarar på en praktisk fråga för den som bygger kortlekar: hur stor är chansen att se minst ett exemplar av ett kort före en viss tur? Ange lekstorlek, exemplar, starthand, dragningar och mulligan för en tur-för-tur-bild.' }, { type: 'paragraph', html: 'Den hypergeometriska fördelningen passar eftersom kort dras utan återläggning. Modellen fungerar för samlarkortspel, brädspel, limited-lekar och andra ändliga kortmängder.' }, { type: 'title', level: 2, text: 'Så läser du dragningens tidslinje' }, { type: 'list', items: ['Starthanden är det första urvalet från den blandade kortleken.', 'Varje tur lägger till det inställda antalet dragna kort.', 'Procenttalet betyder minst ett exemplar, inte exakt ett.', 'Förväntade exemplar är ett separat genomsnitt från träffchansen.'] }, { type: 'title', level: 2, text: 'Mulliganantaganden kan ändras' }, { type: 'paragraph', html: 'Omdragningen modellerar en enkel strategi: behåll en hand med målet; annars ersätt hela handen en gång och fortsätt från den nya vägen. Delvisa mulligans, scry, tutors och beslut om andra kort ingår inte.' }, { type: 'tip', title: 'Använd spelets riktiga regler', html: 'Om ditt spel har en annan starthand, extra dragning eller mulliganprocedur ska du ändra fälten. Svaret beror på reglerna och antalet exemplar.' }, { type: 'title', level: 2, text: 'Den hypergeometriska idén på en rad' }, { type: 'paragraph', html: 'För n kort ur en lek med N kort och K målexemplar är chansen utan träff C(N − K, n) / C(N, n). Kalkylatorn använder komplementet 1 − den chansen för minst ett målkort.' }, { type: 'diagnostic', variant: 'info', title: 'Det här simulerar kalkylatorn inte', badge: 'GRÄNSER', html: 'Den följer inte namngivna kort, urval, ersättningseffekter, scry, tutors, flera mål eller hela spelstatusen. Använd resultatet som bas och modellera extra regler separat.' }],
  faq: [{ question: 'Vilken formel används för kortdragningssannolikhet?', answer: 'För minst ett exemplar i n kort används 1 − C(N − K, n) / C(N, n), där N är lekens storlek och K antalet exemplar.' }, { question: 'Fungerar den för fem dragna kort?', answer: 'Ja. Sätt Starthand till 5 och välj dragningar och turer som passar ditt spel.' }, { question: 'Hur fungerar mulliganalternativet?', answer: 'Dra om efter miss ersätter en gång en starthand utan målkort. Det är enklare än ett spels specifika delvisa mulliganregler.' }, { question: 'Varför skiljer sig förväntade exemplar från träffchansen?', answer: 'Träffchansen frågar om urvalet innehåller ett eller flera exemplar. Förväntade exemplar är det genomsnittliga antalet i urvalet.' }],
  bibliography, howTo: [{ name: 'Ange lekstorlek och exemplar', text: 'Ställ in totala antalet kort och hur många exemplar du söker.' }, { name: 'Matcha hand och dragningar', text: 'Ange starthand, dragna kort per tur och sista tur.' }, { name: 'Välj mulliganmodell', text: 'Använd Ingen mulligan för ett sammanhängande urval eller omdragning för ett helt byte.' }, { name: 'Läs tidslinjen', text: 'Jämför procenten för minst ett exemplar i handen och vid varje tur.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Kalkylator för sannolikhet att dra kort', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Kortdragningssannolikheter för ändliga tabletop-lekar.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Vilken formel används för kortdragningssannolikhet?', acceptedAnswer: { '@type': 'Answer', text: 'Kalkylatorn använder komplementet till den hypergeometriska sannolikheten utan träff.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Beräkna kortdragningssannolikhet', step: [{ '@type': 'HowToStep', name: 'Ställ in lekens regler', text: 'Ange lekstorlek, exemplar, hand, dragningar och turer.' }, { '@type': 'HowToStep', name: 'Läs resultatet', text: 'Jämför chansen att se minst ett exemplar i tidslinjen.' }] }],
};
