import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'kart-cekme-olasilik-hesaplayici', title: 'Kart Çekme Olasılığı Hesaplayıcı',
  description: 'Hipergeometrik dağılımla belirli bir tura kadar bir kartın en az bir kopyasını çekme olasılığını hesaplayın.',
  ui: {
    configureLabel: 'Deste kurallarını ayarla', configureHint: 'Deste, el, çekim ve mulligan varsayımlarını değiştirin. Sonuçlar anında güncellenir.', presetLabel: 'Başlangıç noktası', presetCustom: 'Özel kurallar', presetStandard: '60 kartlık deste · 4 kopya', presetLimited: '40 kartlık deste · 4 kopya', presetSingleton: '100 kartlık deste · 1 kopya', deckSizeLabel: 'Deste boyutu', targetCopiesLabel: 'Kartın kopyaları', openingHandLabel: 'Başlangıç eli', drawsPerTurnLabel: 'Tur başına çekim', throughTurnLabel: 'Şu tura kadar göster', mulliganLabel: 'Mulligan modeli', mulliganNone: 'Mulligan yok', mulliganFullRedraw: 'Kaçırınca yeniden çek', visualLabel: 'Çekim yolun', visualHint: 'Örneğe daha fazla kart girdikçe kart yelpazesi açılır.', openingHandStage: 'Başlangıç eli', turnLabel: 'Tur', cardsSeenLabel: 'Görülen kartlar', finalChanceLabel: 'Son turdaki olasılık', expectedCopiesLabel: 'O zamana kadar beklenen kopya', probabilityByTurnLabel: 'Tura göre olasılık', explanationLabel: 'En az bir kopya', noMulliganNote: 'Mulligan yok: model karıştırılmış desteden tek bir örnek sayar.', fullRedrawNote: 'Kaçırınca yeniden çek: başlangıç elinde hedef yoksa el bir kez tamamen değiştirilir.', invalidInput: 'Devam etmek için deste kurallarını kontrol edin.', invalidDeck: 'Geçerli bir deste boyutu seçin.', invalidCopies: 'Kopya sayısı sıfır ile deste boyutu arasında olmalıdır.', invalidHand: 'Başlangıç eli desteden büyük olamaz.', invalidDraws: 'Tur başına çekim sıfır veya daha fazla olmalıdır.', invalidTurns: 'Sıfır ile 60 arasında bir tur seçin.', cardsLabel: 'kart', copyLabel: 'kopya',
  },
  seo: [{ type: 'title', level: 2, text: 'Deste kart çekme olasılığını hesaplayın' }, { type: 'paragraph', html: 'Bu hesaplayıcı deste kurarken şu pratik soruyu yanıtlar: belirli bir tura kadar bir kartın en az bir kopyasını görme olasılığım nedir? Deste boyutu, kopyalar, başlangıç eli, çekimler ve mulligan kuralını girerek tur tur sonucu görün.' }, { type: 'paragraph', html: 'Kartlar geri konmadan çekildiği için hipergeometrik dağılım kullanılır. Bu model koleksiyon kart oyunları, masa oyunları, limited desteler ve diğer sonlu kart havuzları için uygundur.' }, { type: 'title', level: 2, text: 'Çekim zaman çizelgesi nasıl okunur' }, { type: 'list', items: ['Başlangıç eli, karıştırılmış desteden alınan ilk örnektir.', 'Her tur ayarlanan sayıda kart ekler.', 'Yüzde en az bir kopyayı gösterir; tam olarak bir kopyayı değil.', 'Beklenen kopya ayrı bir ortalamadır ve isabet olasılığıyla aynı şeyi ölçmez.'] }, { type: 'title', level: 2, text: 'Mulligan varsayımları ayarlanabilir' }, { type: 'paragraph', html: 'Yeniden çekme seçeneği basit bir stratejiyi modeller: hedefi içeren eli tut; hedef yoksa eli bir kez tamamen değiştir ve yeni yoldan devam et. Kısmi mulligan, scry, tutor ve diğer kartlara göre kararlar dahil değildir.' }, { type: 'tip', title: 'Oyunun gerçek kurallarını kullanın', html: 'Oyununuzda farklı bir başlangıç eli, ek çekim veya mulligan prosedürü varsa alanları değiştirin. Doğru sonuç kurallara ve kopya sayısına bağlıdır.' }, { type: 'title', level: 2, text: 'Hipergeometrik fikir tek satırda' }, { type: 'paragraph', html: 'N kartlık destede K hedef kopyası varsa, n kartta hedef bulamama olasılığı C(N − K, n) / C(N, n) olur. Hesaplayıcı bunun tümleyenini, 1 − hedefsiz olasılığı, kullanarak en az bir hedef kartı bulma ihtimalini verir.' }, { type: 'diagnostic', variant: 'info', title: 'Bu hesaplayıcı neyi simüle etmez', badge: 'SINIRLAR', html: 'İsimli kartları, seçimleri, değiştirme etkilerini, scry işlemlerini, tutorları, birden çok hedefi veya tam oyun durumunu izlemez. Sonucu temel alın ve ek kuralları ayrıca modelleyin.' }],
  faq: [{ question: 'Kart çekme olasılığı formülü nedir?', answer: 'n kartta en az bir kopya için 1 − C(N − K, n) / C(N, n) kullanılır; N deste boyutu, K kopya sayısıdır.' }, { question: 'Beş kartlık çekim için çalışır mı?', answer: 'Evet. Başlangıç eli değerini 5 yapın ve oyununuzdaki çekim ve turları seçin.' }, { question: 'Mulligan seçeneği nasıl çalışır?', answer: 'Kaçırınca yeniden çek, hedef kopyası olmayan başlangıç elinin bir kez tamamen değiştirilmesini modeller. Oyunlara özel kısmi kurallardan daha basittir.' }, { question: 'Beklenen kopya neden isabet olasılığından farklıdır?', answer: 'İsabet olasılığı örnekte bir veya daha fazla kopya olup olmadığını sorar. Beklenen kopya örnekteki ortalama kopya sayısıdır.' }],
  bibliography, howTo: [{ name: 'Deste boyutunu ve kopyaları girin', text: 'Toplam kart sayısını ve aradığınız kopya sayısını belirleyin.' }, { name: 'El ve çekim kurallarını eşleştirin', text: 'Başlangıç eli, tur başına kart ve gösterilecek son turu girin.' }, { name: 'Mulligan modeli seçin', text: 'Tek örnek için Mulligan yok seçeneğini veya tek tam değişim için kaçırınca yeniden çek seçeneğini kullanın.' }, { name: 'Zaman çizelgesini okuyun', text: 'Başlangıç elinde ve her turda en az bir kopya yüzdesini karşılaştırın.' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Kart Çekme Olasılığı Hesaplayıcı', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: 'Sonlu tabletop desteleri için kart çekme olasılıkları.' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Kart çekme olasılığı formülü nedir?', acceptedAnswer: { '@type': 'Answer', text: 'Hesaplayıcı, hedef bulamamanın hipergeometrik olasılığının tümleyenini kullanır.' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Kart çekme olasılığını hesaplama', step: [{ '@type': 'HowToStep', name: 'Deste kurallarını ayarla', text: 'Deste boyutu, kopyalar, el, çekimler ve turları girin.' }, { '@type': 'HowToStep', name: 'Sonucu okuyun', text: 'Zaman çizelgesinde en az bir kopya görme olasılığını karşılaştırın.' }] }],
};
