import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { CardDrawOddsUI } from '../ui';

export const content: ToolLocaleContent<CardDrawOddsUI> = {
  slug: 'card-draw-odds-calculator', title: '卡牌抽取概率计算器',
  description: '使用超几何分布，计算在指定回合前抽到至少一张目标卡的概率。',
  ui: {
    configureLabel: '设置牌组规则', configureHint: '修改牌组、起手、抽牌和调度规则，结果会立即更新。', presetLabel: '起始方案', presetCustom: '自定义规则', presetStandard: '60张牌组 · 4张', presetLimited: '40张牌组 · 4张', presetSingleton: '100张牌组 · 1张', deckSizeLabel: '牌组大小', targetCopiesLabel: '目标卡数量', openingHandLabel: '起手牌', drawsPerTurnLabel: '每回合抽牌', throughTurnLabel: '显示至回合', mulliganLabel: '调度模型', mulliganNone: '不调度', mulliganFullRedraw: '未命中后重抽', visualLabel: '你的抽牌路径', visualHint: '样本中的牌越来越多时，扇形牌面会展开。', openingHandStage: '起手牌', turnLabel: '回合', cardsSeenLabel: '已看牌数', finalChanceLabel: '最终回合概率', expectedCopiesLabel: '预计看到的目标牌', probabilityByTurnLabel: '按回合查看概率', explanationLabel: '至少一张', noMulliganNote: '不调度：模型只计算洗牌后牌组的一次样本。', fullRedrawNote: '未命中后重抽：起手没有目标牌时，将整手牌替换一次。', invalidInput: '请检查牌组规则后继续。', invalidDeck: '请输入有效的牌组大小。', invalidCopies: '目标牌数量必须在0和牌组大小之间。', invalidHand: '起手牌不能多于牌组。', invalidDraws: '每回合抽牌数不能小于0。', invalidTurns: '请选择0到60之间的回合。', cardsLabel: '张牌', copyLabel: '张',
  },
  seo: [{ type: 'title', level: 2, text: '计算牌组抽到目标卡的概率' }, { type: 'paragraph', html: '这个计算器回答组牌时的实际问题：在指定回合前看到至少一张目标卡的概率是多少？输入牌组大小、目标牌数量、起手牌、每回合抽牌和调度规则，即可查看每回合的变化。' }, { type: 'paragraph', html: '由于抽牌后不会放回，计算使用超几何分布。它适用于集换式卡牌、桌游、限制赛牌组以及其他有限的牌池。' }, { type: 'title', level: 2, text: '如何阅读抽牌时间线' }, { type: 'list', items: ['起手牌是洗牌后牌组的第一份样本。', '每个回合会加入设置数量的牌。', '百分比表示至少一张，而不是刚好一张。', '预计牌数是独立的平均值，与命中概率不同。'] }, { type: 'title', level: 2, text: '调度假设可以调整' }, { type: 'paragraph', html: '重抽选项模拟简单策略：起手有目标卡就保留，没有目标卡时将整手牌替换一次，然后继续计算。它不包含部分调度、占卜、检索或基于其他牌的决策。' }, { type: 'tip', title: '使用游戏的真实规则', html: '如果游戏有不同的起手牌、额外抽牌或调度流程，请修改这些字段。准确结果取决于规则和牌组中的目标牌数量。' }, { type: 'title', level: 2, text: '一行理解超几何分布' }, { type: 'paragraph', html: '从含有N张牌、其中K张目标牌的牌组中看n张时，没有目标牌的概率是 C(N − K, n) / C(N, n)。计算器使用其补集，得到至少一张目标牌的概率。' }, { type: 'diagnostic', variant: 'info', title: '本计算器不会模拟什么', badge: '限制', html: '它不会追踪具体牌名、选牌、替换效果、占卜、检索、多个目标或完整的游戏状态。请把结果当作基准，再单独处理额外规则。' }],
  faq: [{ question: '抽牌概率使用什么公式？', answer: '在n张牌中至少有一张目标牌的概率是 1 − C(N − K, n) / C(N, n)，其中N是牌组大小，K是目标牌数量。' }, { question: '可以计算抽5张牌吗？', answer: '可以。把起手牌设置为5，并按照游戏规则填写抽牌数和回合。' }, { question: '调度选项如何计算？', answer: '未命中后重抽表示将没有目标牌的起手整手替换一次，比具体游戏的部分调度规则更简单。' }, { question: '预计牌数为什么不同于命中概率？', answer: '命中概率只询问样本中是否有一张或更多目标牌，预计牌数表示样本中的平均数量。' }],
  bibliography, howTo: [{ name: '输入牌组大小和目标数量', text: '设置牌组总数以及想抽到的目标牌数量。' }, { name: '匹配起手和抽牌规则', text: '填写起手牌、每回合抽牌数和最后显示的回合。' }, { name: '选择调度模型', text: '连续样本选择不调度，需要整手替换时选择未命中后重抽。' }, { name: '阅读时间线', text: '比较起手和每个回合看到至少一张目标牌的概率。' }],
  schemas: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: '卡牌抽取概率计算器', applicationCategory: 'GameApplication', operatingSystem: 'Web', description: '用于有限桌游牌组的抽牌概率计算器。' }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: '抽牌概率使用什么公式？', acceptedAnswer: { '@type': 'Answer', text: '计算器使用没有目标牌的超几何概率的补集。' } }] }, { '@context': 'https://schema.org', '@type': 'HowTo', name: '计算抽牌概率', step: [{ '@type': 'HowToStep', name: '设置牌组规则', text: '输入牌组大小、目标数量、起手、抽牌和回合。' }, { '@type': 'HowToStep', name: '查看结果', text: '在时间线中比较看到至少一张目标牌的概率。' }] }],
};
